on:
  push:
    branches:    
      - 'master'
  schedule:
  - cron: '0 0 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/checkout@v2
      with:
        repository: 'ScoopInstaller/Main'
        fetch-depth: 1
        path: 'Main'
    - uses: actions/checkout@v2
      with:
        repository: 'ScoopInstaller/Extras'
        fetch-depth: 1
        path: 'Extras'
    - uses: actions/checkout@v2
      with:
        repository: 'ScoopInstaller/Versions'
        fetch-depth: 1
        path: 'Versions'
    - uses: actions/checkout@v2
      with:
        repository: 'ScoopInstaller/Java'
        fetch-depth: 1
        path: 'Java'
    - name: Update bucket
      run: |
        cp -rf Main/bucket/*          ./bucket
        cp -rf Main/scripts/*         ./scripts
        cp -rf Extras/bucket/*        ./bucket
        cp -rf Extras/scripts/*       ./scripts
        cp -rf Versions/bucket/*      ./bucket
        cp -rf Versions/scripts/*     ./scripts
        cp -rf Java/bucket/*          ./bucket

        perl -pi -e 's/github\.com\/(.+)\/releases\/download/download\.fastgit\.org\/$1\/releases\/download/g' ./bucket/*.json
        perl -pi -e 's/raw\.githubusercontent\.com/raw\.fastgit\.org/g' ./bucket/*.json
        
        # 7zip
        perl -pi -e 's/7-zip\.org\/a/experiments\-alicdn\.sparanoid\.net\/7z/g' ./bucket/7zip.json

        # latex
        perl -pi -e 's/miktex\.org\/download\/ctan/mirrors\.aliyun\.com\/CTAN/g' ./bucket/latex.json

        # nodejs
        perl -pi -e 's/nodejs\.org\/dist/npm\.taobao\.org\/mirrors\/node/g' ./bucket/nodejs*.json

        # vlc
        perl -pi -e 's/download\.videolan\.org\/pub/mirrors\.ustc\.edu\.cn\/videolan\-ftp/g' ./bucket/vlc.json

        # dbeaver
        perl -pi -e 's/download\.dbeaver\.com\/community/download\.fastgit\.org\/dbeaver\/dbeaver\/releases\/download/g' ./bucket/dbeaver.json

        rm -rf Main Extras Versions Java
        
        # install.ps1
        curl -o install.ps1 https://raw.fastgit.org/scoopinstaller/install/master/install.ps1
        perl -pi -e 's/github\.com/hub\.fastgit\.xyz/g' ./install.ps1

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Updated"
        git push
