on:
  push:
    branches:    
      - 'master'
  schedule:
  - cron: '0 * * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/checkout@v2
      with:
        repository: 'ScoopInstaller/Main'
        fetch-depth: 1
        path: 'Main'
    - uses: actions/checkout@v2
      with:
        repository: 'lukesampson/scoop-extras'
        fetch-depth: 1
        path: 'scoop-extras'
    - uses: actions/checkout@v2
      with:
        repository: 'ScoopInstaller/Versions'
        fetch-depth: 1
        path: 'Versions'
    - uses: actions/checkout@v2
      with:
        repository: 'scoopinstaller/Java'
        fetch-depth: 1
        path: 'Java'
    - uses: actions/checkout@v2
      with:
        repository: 'duzyn/scoop'
        fetch-depth: 1
        path: 'scoop'
    - name: Update bucket
      run: |
        cp -rf Main/bucket/*         ./bucket
        cp -rf scoop-extras/bucket/* ./bucket
        cp -rf Versions/bucket/*     ./bucket
        cp -rf Java/bucket/*         ./bucket
        cp -rf scoop/bucket/*        ./bucket

        perl -pi -e 's/github\.com\/(.+)\/releases\/download/download\.fastgit\.org\/$1\/releases\/download/g' ./bucket/*.json
        perl -pi -e 's/raw\.githubusercontent\.com/raw\.fastgit\.org/g' ./bucket/*.json

        # latex
        perl -pi -e 's/miktex\.org\/download\/ctan/mirrors\.aliyun\.com\/CTAN/g' ./bucket/latex.json

        # nodejs
        perl -pi -e 's/nodejs\.org\/dist/npm\.taobao\.org\/mirrors\/node/g' ./bucket/nodejs*.json

        # vlc
        perl -pi -e 's/download\.videolan\.org\/pub/mirrors\.ustc\.edu\.cn\/videolan\-ftp/g' ./bucket/vlc.json

        # dbeaver
        perl -pi -e 's/download\.dbeaver\.com\/community/download\.fastgit\.org\/dbeaver\/dbeaver\/releases\/download/g' ./bucket/dbeaver.json

        # firefox
        cp ./bucket/firefox.json ./bucket/firefox-zh-cn.json
        perl -pi -e 's/en-US/zh-CN/g' ./bucket/firefox-zh-cn.json

        rm -rf Main scoop-extras Versions Java scoop

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
